### ISSUE TITLE
12/4 남은 task 및 최종 역할 분담 

### ISSUE THREAD

**Issue by GaYoung28** [ssginc-be/Pickypal-WMS#68]
@Queue-ri 
- [x] #69
- [x] #71
- [x] #63
- [x] #73
- [x] #76

@Hyun7en 
- [x] #59

@GaYoung28 @HeeJava 
- [x] #60

**Comment by newbackjava** [comment]
🎉 트렐로/깃을 통한 개발과정을 함께 진행하신 것만 해도
     의미있는 프로젝트 이셨을 듯합니다.!
     깃 연동/컨벤션 등 너무 잘하셨어요!!! 🐞 ✌️

**Comment by HeeJava** [comment]
감히 미니 프로젝트라 말할 수 없는 어려운 프로젝트였지만 팀장님과 팀원분들과 함께 할 수 있어서 좋았다...
다음에도 같은 조..? (죄송합니다) 다들 오늘 푹 주무세요..!!^^
`System.exit(0);`  ^o^

**Comment by GaYoung28** [comment]
저두요 ㅎㅎ 마지막까지 정말 다들 고생많으셨고 .. 낼도 화이팅입니다~~!!

**Comment by Hyun7en** [comment]
포스트맨에서 구현 안 한 기능이 있는 것 같습니다. 관리자 모드가 있는데 그건 어떻게 하실 건지 다른 분들께 여쭤봅니다
localhost:8080/backdoor/ship?order_id=1(출고중 -> 출고완료 처리하는 프로세스) 가 빠진거 같은데 어떻게 생각하시나요

**Comment by Queue-ri** [comment]
> 포스트맨에서 구현 안 한 기능이 있는 것 같습니다. 관리자 모드가 있는데 그건 어떻게 하실 건지 다른 분들께 여쭤봅니다 localhost:8080/backdoor/ship?order_id=1(출고중 -> 출고완료 처리하는 프로세스) 가 빠진거 같은데 어떻게 생각하시나요

@Hyun7en 그거 출고 중인 상품을 강제로 배송 완료 시키는 가상 api인데, `BackdoorScreen` 클래스 추가해서 해당 api 붙였습니다!

https://github.com/ssginc-be/Pickypal-WMS/blob/04d936b3865fc8dbef43c3a2a8635331b36f252c/cli/src/main/java/com/pickypal/screen/BackdoorScreen.java#L121-L127

하단과 같이 DB에도 반영되는거 확인했습니다

![image](https://github.com/user-attachments/assets/e48311d1-acde-4144-a738-9a36d2533452)


질문해주셔서 감사해요~

**Comment by Hyun7en** [comment]
> > 포스트맨에서 구현 안 한 기능이 있는 것 같습니다. 관리자 모드가 있는데 그건 어떻게 하실 건지 다른 분들께 여쭤봅니다 localhost:8080/backdoor/ship?order_id=1(출고중 -> 출고완료 처리하는 프로세스) 가 빠진거 같은데 어떻게 생각하시나요
> 
> @Hyun7en 그거 출고 중인 상품을 강제로 배송 완료 시키는 가상 api인데, `BackdoorScreen` 클래스 추가해서 해당 api 붙였습니다!
> 
> https://github.com/ssginc-be/Pickypal-WMS/blob/04d936b3865fc8dbef43c3a2a8635331b36f252c/cli/src/main/java/com/pickypal/screen/BackdoorScreen.java#L121-L127
> 
> 하단과 같이 DB에도 반영되는거 확인했습니다
> 
> ![image](https://private-user-images.githubusercontent.com/77003554/392345586-e48311d1-acde-4144-a738-9a36d2533452.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMTAzMTgsIm5iZiI6MTczMzMxMDAxOCwicGF0aCI6Ii83NzAwMzU1NC8zOTIzNDU1ODYtZTQ4MzExZDEtYWNkZS00MTQ0LWE3MzgtOWEzNmQyNTMzNDUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDExMDAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkZGRjZWJmZmMwMWM1MDlmOGYxNTM0M2RhNTU3NDMwYzVjZmRlMmEzYjRmZWVmOTNlOWNiYTZkY2QyNDNkNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vc7v5qLiTOQJCGvRSxAUK-w1XGSU8ZLSEUlFbqdIWyA)
> 
> 질문해주셔서 감사해요~

**Comment by GaYoung28** [comment]
- #69 

access token을 헤더로 받고 그것을 기반으로 branch_id를 가져오셨다는 말이 잘 이해가 되지 않습니다 혹시 설명해주실수 있나요?

**Comment by HeeJava** [comment]
파이어베이스 연동하면서 토큰이 왔다갔다 했을텐데 어떤 느낌인지 이해가 되지 않습니다.
머리 속에 그릴 수 있게 쉽게 설명해주실 수 있나요?

**Comment by Queue-ri** [comment]
> access token을 헤더로 받고 그것을 기반으로 branch_id를 가져오셨다는 말이 잘 이해가 되지 않습니다 혹시 설명해주실수 있나요?

@GaYoung28 access token은 JWT 토큰인데요, 하단과 같이 payload에 정보가 들어있습니다.

![image](https://github.com/user-attachments/assets/7aa58265-c885-4afa-ac0d-30ecb80797f8)

그리고 요걸 `JwtKit`에서 파싱해서 사용자ID를 가져옵니다.

https://github.com/ssginc-be/Pickypal-WMS/blob/04d936b3865fc8dbef43c3a2a8635331b36f252c/api/src/main/java/com/pickypal/api/auth/JwtKit.java#L40-L45

사용자ID는 `service_user` 테이블의 PK고요, 이걸 기반으로 사용자 테이블을 조회하면 `branch_id` 값을 알아낼 수 있습니다.

![image](https://github.com/user-attachments/assets/9e6ec503-9cf7-43e6-8823-4def5f5b50c0)
